### ISSUE TITLE
请问如何与邦德大神那个软件一起使用呢？

### ISSUE THREAD

**Issue by athunder2020** [wanghuisenior/xxqg_tiku#1]
请问如何与邦德大神那个软件一起使用呢？

**Comment by wanghuisenior** [comment]
没源码搞不了

**Comment by szsyzx** [comment]
@wanghuisenior 老大在吗可以看下如何对接德邦的软件吗 源码我有

**Comment by wanghuisenior** [comment]
> @wanghuisenior 老大在吗可以看下如何对接德邦的软件吗 源码我有

在答题函数获取到问题和答案的地方调用该函数：updateToServer(question,answer)即可。
