### ISSUE TITLE
大神 

### ISSUE THREAD

**Issue by Kiss-YuJiu** [wanghuisenior/xxqg_tiku#2]
大神  能否给个联系方式 我不会用Python 但是很想用

**Comment by wanghuisenior** [comment]
只需要安装python就行了不会的可以提问题

**Comment by Kiss-YuJiu** [comment]
已解决，谢谢大神提供的资源发自我的华为手机-------- 原始邮件 --------发件人： "Mr.Simple" <notifications@github.com>日期： 2021年1月18日周一 07:57收件人： wanghuisenior/xxqg_tiku <xxqg_tiku@noreply.github.com>抄送： nanmeng-sujin <169231774@qq.com>, Author <author@noreply.github.com>主    题： Re: [wanghuisenior/xxqg_tiku] 大神  (#2)

只需要安装python就行了不会的可以提问题
