### ISSUE TITLE
大佬，为什么获取答案时报500错误

### ISSUE THREAD

**Issue by Gingmzmzx** [wanghuisenior/xxqg_tiku#5]
ip是本地ip，公网访问不了，我用的是ngrok映射，然后获取答案时就500

**Comment by wanghuisenior** [comment]
你程序跑起来报错不，先试试本地正常不

**Comment by Gingmzmzx** [comment]
在autojs中不会报错，本地运行也会报500

**Comment by Gingmzmzx** [comment]
虽然autojs不报错，但获取不到

**Comment by Gingmzmzx** [comment]
![image](https://user-images.githubusercontent.com/49107602/110319591-139e2a80-804a-11eb-8c54-9092a8dcc413.png)

**Comment by wanghuisenior** [comment]
你本地运行，浏览器访问： 127.0.0.1:8000/getAnswerByQuestion?question=铁路是由、和组成的一个整体工程结构。
看看能否获取到答案： ABC

**Comment by Gingmzmzx** [comment]
![image](https://user-images.githubusercontent.com/49107602/110892685-75eb7980-832f-11eb-91e6-f3b1f0f90aee.png)
还是不行

**Comment by wanghuisenior** [comment]
> ![image](https://user-images.githubusercontent.com/49107602/110892685-75eb7980-832f-11eb-91e6-f3b1f0f90aee.png)
> 还是不行

你联系我把qq154306777
