### ISSUE TITLE
服务跑起来了，脚本怎么远程获取参数

### ISSUE THREAD

**Issue by jikkyfu** [wanghuisenior/xxqg_tiku#6]
当本地数据库没有的时候，如何获取远程参数？

**Comment by wanghuisenior** [comment]
啥啊，你自己能看懂你问的啥吗

**Comment by jikkyfu** [comment]
不好意思，
我是说当答题的时候，如果本地数据库没有的时候，能否从这个服务器远程调用答题数据。
另外能否将错误的题库加入数据库，选择的时候排除它。

**Comment by wanghuisenior** [comment]
我那写的很清楚了 function getAnswerByQuestion(question) {
     var ans = http.get("http://服务器IP:端口/getAnswerByQuestion?question="+question);
     return ans;
 }应该可以

**Comment by wanghuisenior** [comment]
另外能否将错误的题库加入数据库，选择的时候排除它。
这个需要根据业务逻辑自己改代码
