### ISSUE TITLE
我是个新手  就想问问怎么在服务器搭建

### ISSUE THREAD

**Issue by Orzyiii** [wanghuisenior/xxqg_tiku#8]
我买了一个服务器  然后按照前辈教程 一步一步都弄完了   但是无论我怎么研究   外网就是访问不了
![image](https://user-images.githubusercontent.com/86647919/137460462-af313a04-ae66-48e8-9f20-cd5ba028a7b6.png)
服务器里的浏览器  可以访问正常

**Comment by wanghuisenior** [comment]
你改代码了啊，  跑起来ip是0.0.0.0
